name: Test code review with openapi
on:
  issue_comment:
    types: [created]

jobs: 
  test_code_review:
    if: >
      github.event.issue.pull_request != null &&
      contains(github.event.comment.body, '/review')
    runs-on: ubuntu-latest
    steps:
      - uses: fiqryq/rebotai@master
        with:
          gh-token: ${{ secrets.GH_TOKEN }}
          openai-api-key: ${{ secrets.OPENAI_API_KEY }}
          model: ${{ vars.MODEL }}
          language: ${{ vars.LANGUAGE }}
